services:
  sensor:
    build:
      context: ./sensors
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SENSOR_ID: ${SENSOR_ID:-1}
    depends_on:
      - kafka
    deploy:
      replicas: 5